name: Monitor 1on1 Meetings

on:
  schedule:
    # Every 5 minutes during business hours (9 AM - 6 PM UTC), Monday-Friday
    - cron: '*/5 9-18 * * 1-5'
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Run in test mode'
        required: false
        default: 'false'
        type: boolean

jobs:
  monitor-meetings:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Monitor meetings
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        ZENDESK_SUBDOMAIN: ${{ secrets.ZENDESK_SUBDOMAIN }}
        ZENDESK_EMAIL: ${{ secrets.ZENDESK_EMAIL }}
        ZENDESK_API_TOKEN: ${{ secrets.ZENDESK_API_TOKEN }}
        GOOGLE_CREDENTIALS_JSON: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        TEST_MODE: ${{ github.event.inputs.test_mode || 'false' }}
      run: |
        if [ "$TEST_MODE" = "true" ]; then
          python github_actions_runner.py --test
        else
          python github_actions_runner.py
        fi
